# Generated by Django 5.1.4 on 2025-01-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departamentos',
            new_name='Departamento',
        ),
    ]
